version: '3'
services:
  app: # frontend
    image: phonebook-front-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend: # backend
    image: phonebook-back-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app
    ports:
      - 5001:5001
    container_name: phonebook-back-prod
  
  debug-helper:
    image: busybox

